services:
  event-proxy-server:
    container_name: event-proxy-server
    build:
      context: .
      dockerfile: ./event-proxy-server/Dockerfile
    ports:
      - "4365:4365" # http
      - "4366:4366" # smtp
    environment:
      EVENT_PROXY_SERVER_XMS: 128m
      EVENT_PROXY_SERVER_XMX: 128m
      # http and smtp servers
      HTTP_PORT: 4365
      SSE_HEARTBEAT_INTERVAL_SEC: 10
      SSE_HANDSHAKE_PENDING_SEC: 180
      SMTP_PORT: 4366
      SMTP_THREAD_POOL_SIZE: 10
      SMTP_QUEUE_CAPACITY: 10
      SMTP_SENDER_SUFFIX: event-proxy-system
      # database
      DB_PATH: events.db
      DB_POOL_SIZE: 5
      # session
      SESSION_TTL_SEC: 7200
      SESSION_CLEAR_INTERVAL_SEC: 3600
      # account
      ACCOUNT_USERNAME: admin
      ACCOUNT_PASSWORD_LENGTH: 20
      ACCOUNT_PASSWORD_HASH_STRENGTH: 10
    networks:
      - event-proxy-system-network

networks:
  event-proxy-system-network:
    driver: bridge
