name: Build, create docker image and send to Dockerhub event proxy server app

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/server-docker.yml"
      - "event-proxy-server/**"
      - "mvnw"
      - "pom.xml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
          check-latest: false
          cache: "maven"

      - name: Change wrapper permissions
        run: chmod +x ./mvnw

      - name: Clean and package to JAR
        run: ./mvnw clean package -pl event-proxy-server

      - name: Upload generated JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-build-context
          path: |
            event-proxy-server/.bin/event-proxy-server.jar
            event-proxy-server/docker/entrypoint
            event-proxy-server/Dockerfile.pipeline
          retention-days: 1

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download generated JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: server-build-context
          path: event-proxy-server/*

      - name: Set up builder
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./event-proxy-server/Dockerfile.pipeline
          push: true
          tags: milosz08/event-proxy-server:latest

      - name: Logout from Docker Hub
        run: docker logout
