name: Update Dockerhub event proxy server README

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/server-docker-readme.yml"
      - "docker/README.md"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: milosz08/event-proxy-server
          readme-filepath: ./docker/README.md
          short-description: "A lightweight event proxy server with fake SMTP service working in local network."
